version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: "Run Scan"
          command: |
            wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
            tar -xzvf ScaResolver-linux64.tar.gz
            rm -rf ScaResolver-linux64.tar.gz
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            /home/linuxbrew/.linuxbrew/bin/brew install checkmarx/ast-cli/ast-cli
            /home/linuxbrew/.linuxbrew/Cellar/ast-cli/*/bin/cx \
            scan create \
            -s . \
            --agent CircleCI \
            --project-name $CIRCLE_PROJECT_REPONAME \
            --branch $CIRCLE_BRANCH \
            --base-uri $CX_BASE_URI \
            --tenant $CX_TENANT \
            --client-id $CX_CLIENT_ID \
            --client-secret $CX_CLIENT_SECRET \
            --sast-incremental \
            --sca-resolver ./ScaResolver \
            $ADDITIONAL_PARAMS
