version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: "Run Scan"
          command: |
            pushd ..
            wget https://github.com/Checkmarx/ast-cli/releases/download/2.0.36/ast-cli_2.0.36_linux_x64.tar.gz
            tar xzvf ast-cli_*.tar.gz
            wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
            tar -xzvf ScaResolver-linux64.tar.gz
            rm -rf ScaResolver-linux64.tar.gz
            popd
            ../cx \
            scan create \
            -s . \
            --agent CircleCI \
            --project-name $CIRCLE_PROJECT_REPONAME \
            --branch $CIRCLE_BRANCH \
            --base-uri $CX_BASE_URI \
            --tenant $CX_TENANT \
            --client-id $CX_CLIENT_ID \
            --client-secret $CX_CLIENT_SECRET \
            --sast-incremental \
            --sca-resolver ../ScaResolver \
            $ADDITIONAL_PARAMS
